---

#debug: true

spring:
  datasource:
    url: jdbc:sqlserver://192.168.64.2:1401;databaseName=db
    username: sa
    password: Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.SQLServerDialect
    hibernate.ddl-auto: update
    show-sql: true

security.user.password: password
