---

debug: true

spring:
  datasource:
    url: jdbc:microsoft:sqlserver://192.168.64.2:1401
    username: sa
    password: Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
